AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Description: Etapa de implantação. Utilizada também para definir ambiente de execução.
    Type: String
    AllowedValues:
      - prod
      - stage
      - dev
    Default: dev
  MemorySize:
    Description: Tamanho da memória da Function.
    Type: String
    Default: "256"

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        ENVIRONMENT: !Ref StageName

Conditions:
  DevelopmentOnlyResources: !Equals
    - !Ref StageName
    - dev

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        ApiKeyRequired: true
        Authorizers:
          CognitoAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt CognitoAuthorizerFunction.Arn
            Identity:
              Header: Authorization # Deverá conter o CPF do cliente

  CognitoAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/cognitoAuthorizer.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: !Ref MemorySize

  # Usado apenas para testes locais
  DestinationTestFunction:
    Condition: DevelopmentOnlyResources # Evita criar o Lambda em produć
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/destinationTest.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: !Ref MemorySize
      Events:
        TestAuthorizer:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /test
            Method: GET
